name: node

on:
  pull_request:
    paths-ignore:
      - "**.md"
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn
      - run: yarn pretty
      - run: yarn build:ts
      - run: yarn test:services
      - run: yarn test:routes
      - run: yarn test:coverage
